#!/bin/sh

BASENAME=extra_2M
NAME=$BASENAME.db
DIR=share
DB=$DIR/$NAME
POD=$DIR/$BASENAME.pod
VERSION=3.1
DATE='April 26, 2025'

rm -f "$DB" "$POD"
mkdir -p "$DIR"
bzcat data/extra_*.txt.bz2 |maint/fill_pds -z -c -f "$DB"
maint/fill_pds -r200000- -L -a -f "$DB" data/pdl_*.txt
maint/fill_spaces -C -f "$DB" data/spc_extra_*.txt
maint/make_pod --version=$VERSION --version_date="$DATE" --name=$NAME \
    --summary='database with special planar difference set samples' \
    <<'EOT' >"$POD"
This file is a supplement to the default database distributed
with the Perl 5 module Math::DifferenceSet::Planar.

It contains some larger cyclic planar difference sets together with
space metadata.  Currently, these are the standard reference sets of
orders 262139, 262144, 524288, 1048576, 2096993, 2097023, 2097152,
4194304, and 8388608, and lex reference sets of most of these orders.
The collection may be extended from time to time.

The total numbers of cyclic planar differerence sets of orders
2096993 and 2097023 are 6,445,655,386,288,147,189,605,602, and
6,383,441,485,627,927,292,616,300, respectively.  These sets
have 3 multipliers.  As 2097152 is a 21st power, there are only
302,819,463,165,789,483,798,528 cyclic planar difference sets of
order 2097152, while these sets have 63 multipliers.

There are 2,639,401,302,619,417,322,137,536 sets of order 4,194,304
with 66 multipliers and 61,512,563,201,650,439,030,921,076 sets of
order 8,388,608 with 69 multipliers.

Standard reference sets are used to calculate unique I<lambda>
and I<theta> values identifying each set.  For example, the
planar difference set generated from the primitive polynomial
I<x^3+x-11 (mod 4,397,381,739,043)> is the reference set, multiplied by
I<549,196,322,429 [lambda]>, plus I<1,841,964,303,308 [theta]>.
EOT

