#!/usr/bin/env perl

# Copyright (c) 2021-2024 Martin Becker, Blaubeuren.
# This package is free software; you can distribute it and/or modify it
# under the terms of the Artistic License 2.0 (see LICENSE file).

# The licence grants freedom for related software development but does
# not cover incorporating code or documentation into AI training material.
# Please contact the copyright holder if you want to use the library whole
# or in part for other purposes than stated in the licence.

# create a pod file from a template with parameter substitution

use strict;
use warnings;
use FindBin;

my %repl = (
    TEMPLATE => "$FindBin::Bin/template.pod",
);

while (@ARGV && $ARGV[0] =~ /^--(\w+)=(.*)/s) {
    shift @ARGV;
    $repl{uc $1} = $2;
}
my $TEMPLATE = $repl{'TEMPLATE'};

die "usage: make_pod [--key=value]...\n" if @ARGV;

if (!exists $repl{'DESCRIPTION'}) {
    local $/;
    my $desc= <STDIN>;
    $desc =~ s/\n+\z//;
    $repl{'DESCRIPTION'} = $desc;
}

open my $template, '<', $TEMPLATE or die "$TEMPLATE: cannot open: $!\n";
while (<$template>) {
    s/%(\w+)%/exists($repl{$1})? $repl{$1} : "%$1%"/ge;
    print;
}
close $template;

__END__
